import { Download } from 'lucide-react';
import jsPDF from 'jspdf';
import type { PredictionResponse, PredictionRequest } from '../types';
import './ExportPDF.css';

interface ExportPDFProps {
    prediction: PredictionResponse;
    request: PredictionRequest;
    location: string;
}

export default function ExportPDF({ prediction, request, location }: ExportPDFProps) {
    const generatePDF = () => {
        const doc = new jsPDF();

        // Title
        doc.setFontSize(20);
        doc.setTextColor(14, 165, 233);
        doc.text('Flood Risk Prediction Report', 20, 20);

        // Date
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 30);

        // Location
        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.text('Location Information', 20, 45);
        doc.setFontSize(11);
        doc.text(`Location: ${location}`, 20, 53);
        doc.text(`Latitude: ${request.lat.toFixed(4)}`, 20, 60);
        doc.text(`Longitude: ${request.lon.toFixed(4)}`, 20, 67);
        doc.text(`Elevation: ${request.elevation.toFixed(1)} m`, 20, 74);

        // Prediction Results
        doc.setFontSize(14);
        doc.text('Prediction Results', 20, 90);

        // Risk Level with color
        const riskColors: Record<string, [number, number, number]> = {
            'Low': [16, 185, 129],
            'Medium': [245, 158, 11],
            'High': [239, 68, 68],
        };

        doc.setFontSize(11);
        doc.text('Risk Level:', 20, 98);
        doc.setTextColor(...riskColors[prediction.risk_level]);
        doc.setFontSize(16);
        doc.text(prediction.risk_level, 60, 98);

        doc.setTextColor(0);
        doc.setFontSize(11);
        doc.text(`Flood Probability: ${(prediction.flood_probability * 100).toFixed(1)}%`, 20, 108);
        doc.text(`Confidence: ${(prediction.confidence * 100).toFixed(1)}%`, 20, 115);
        doc.text(`Flood Predicted: ${prediction.is_flood_predicted ? 'Yes' : 'No'}`, 20, 122);

        // Environmental Data
        doc.setFontSize(14);
        doc.text('Environmental Data', 20, 138);
        doc.setFontSize(11);
        doc.text(`Slope: ${request.slope.toFixed(2)} degrees`, 20, 146);
        doc.text(`Land Cover: ${request.landcover}`, 20, 153);

        // Precipitation
        doc.setFontSize(14);
        doc.text('Precipitation Data', 20, 169);
        doc.setFontSize(11);
        doc.text(`1-Day Total: ${request.precip_1d.toFixed(1)} mm`, 20, 177);
        doc.text(`3-Day Total: ${request.precip_3d.toFixed(1)} mm`, 20, 184);
        doc.text(`7-Day Total: ${request.precip_7d.toFixed(1)} mm`, 20, 191);
        doc.text(`14-Day Total: ${request.precip_14d.toFixed(1)} mm`, 20, 198);

        // River Discharge
        doc.setFontSize(14);
        doc.text('River Discharge', 20, 214);
        doc.setFontSize(11);
        doc.text(`Last Discharge: ${request.dis_last.toFixed(1)} m³/s`, 20, 222);
        doc.text(`3-Day Trend: ${request.dis_trend_3.toFixed(1)} m³/s`, 20, 229);

        // Footer
        doc.setFontSize(9);
        doc.setTextColor(150);
        doc.text('Bangladesh Flood Prediction System', 20, 280);
        doc.text('This report is generated by AI and should be used as guidance only.', 20, 285);

        // Save
        doc.save(`flood-prediction-${Date.now()}.pdf`);
    };

    return (
        <button onClick={generatePDF} className="export-pdf-btn">
            <Download size={18} />
            Export PDF Report
        </button>
    );
}
